/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "admin_pw_hash_1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "admin_un_hash_1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api_key_abuse_ipdb": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api_key_google_1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "audit_api_secret_1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "audit_api_secret_2": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "cookie_secret_1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "cookie_secret_2": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "cookie_secret_3": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "cookie_secret_4": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "cron_job_secret_1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "session_secret_1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "session_secret_2": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "session_secret_3": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "webaudit_function2": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "webaudit_react_app": {
      "type": "sst.aws.React"
      "url": string
    }
    "webaudit_table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "webaudit_table_audit_v1": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}

import "sst"
export {}