import { Form, useActionData, type ActionFunctionArgs } from "react-router"
// import { get_http_observatory_v1 } from "~/audit_api/api_calls/get_http_observatory_v1"
import { handler } from "~/audit_api/v1/create_stats_cron_job"
// import type { Route } from "./+types/dev"
import { parseJSON } from "~/common/shared/misc"
import { putDynamoDBBulk } from "~/common/utils/server/dynamodb.server"
// import { frequencyStats } from "~/audit_api/helpers/calculate_stats"



export const action = async ({ request }: ActionFunctionArgs) => {
    const formadata = await request.formData()

    const type = formadata.get('type') ?? ''
    //     const res = await get_http_observatory_v1('https://www.linkedin.com')

    if (type === "action") {
        const res = await handler()

        console.log({ res })


        return res
    } else if (type === "upload") {
        const payload = formadata.get('payload')

        const parsed = parseJSON(payload)

        if (parsed && Array.isArray(parsed)) {
            for (let i = 0; i < parsed.length; i += 1) {
                const up = await putDynamoDBBulk(parsed, '_table_audit_v1')
            }
        }
    }

    return null
}


const getSumFromArr = (na: number[]) => {
    let count = 0
    for (let i = 0; i < na.length; i += 1) {
        count += na[i]
    }
    return count
}

export default function DevRoute() {

    const actionData = useActionData()
    console.log({ actionData })

    
    // testing stats accuracy

    const clientClick1 = () => {

        const { score_c, score_e, score_main, score_o, score_s } = dummyStatsStore
        const sum = getSumFromArr(score_main)
        const sum_e = getSumFromArr(score_e)
        const sum_c = getSumFromArr(score_c)
        const sum_o = getSumFromArr(score_o)
        const sum_s = getSumFromArr(score_s)


        console.log({
            sum_c,
            sum_o,
            sum_s, sum, sum_e

        })

    }


    return (
        <div className="flex flex-col gap-4">
            <div className="text-2xl text-red-900 dark:text-red-100">DEV ROUTE</div>
            <div className="p-2 bg-neutral-100 dark:bg-neutral-900 flex">
                <Form method="post" >
                    <input className="bg-red-500 p-2" type="submit" value="Action" />
                    <input type="hidden" name="type" value="action" />
                </Form>

            </div>

            <div className="p-2 bg-neutral-100 dark:bg-neutral-900 flex">
                <Form method="post" className="flex gap-2 w-full">
                    <input className="bg-red-500 p-2" type="submit" value="Upload Bulk" />
                    <textarea className="bg-red-100 dark:bg-red-900 grow" name="payload" />
                    <input type="hidden" name="type" value="upload" />
                </Form>
            </div>


            <div className="p-2 bg-neutral-100 dark:bg-neutral-900 flex">
                <button type="button" className="bg-red-500 p-2" onClick={() => clientClick1()}>
                    Client click
                </button>
            </div>


            {actionData && (
                <pre>
                    {JSON.stringify(actionData, null, 2)}
                </pre>
            )}
        </div>
    )
}




const dummyStatsStore = {
    "created_at": 1769158403756,
    "score_main": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        0,
        1,
        1,
        2,
        2,
        5,
        2,
        4,
        6,
        0,
        0,
        0,
        0,
        3,
        4,
        4,
        4,
        2,
        1,
        1,
        2,
        0,
        1,
        1,
        0,
        1,
        3,
        1,
        2,
        0,
        2,
        1,
        1,
        1,
        0,
        0,
        1,
        1,
        0,
        2,
        2,
        0,
        1,
        0,
        0,
        3,
        1,
        1,
        1,
        0,
        1,
        1,
        0,
        0,
        0
    ],
    "score_c": [
        61,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        5,
        0,
        1,
        1,
        0,
        1,
        1,
        0,
        1,
        3
    ],
    "score_e": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        2,
        0,
        1,
        1,
        3,
        2,
        0,
        2,
        3,
        1,
        3,
        1,
        3,
        1,
        3,
        4,
        1,
        0,
        1,
        1,
        5,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        2,
        1,
        1,
        0,
        2,
        2,
        3,
        0,
        1,
        1,
        0,
        2,
        1,
        0,
        2,
        0,
        2,
        1,
        1,
        4,
        2,
        2,
        1,
        0,
        0,
        0,
        2,
        1,
        0,
        0,
        1,
        1,
        1,
        3,
        3,
        1,
        0,
        0,
        1
    ],
    "score_s": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        9,
        0,
        1,
        0,
        1,
        6,
        1,
        4,
        1,
        0,
        7,
        1,
        4,
        0,
        1,
        3,
        0,
        8,
        0,
        0,
        10,
        0,
        18,
        1,
        0,
        6,
        0,
        5,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        3
    ],
    "score_o": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        2,
        1,
        3,
        0,
        2,
        2,
        1,
        1,
        2,
        2,
        1,
        2,
        2,
        0,
        1,
        4,
        1,
        4,
        6,
        9,
        4,
        7,
        3,
        9,
        3,
        5,
        5,
        14
    ],
    "stats_score_main": [
        43,
        100,
        62,
        50,
        53,
        76,
        91,
        18.5,
        110.5,
        66,
        76
    ],
    "stats_score_c": [
        0,
        100,
        0,
        0,
        0,
        34,
        91,
        -51,
        85,
        23,
        92
    ],
    "stats_score_e": [
        21,
        100,
        62,
        38,
        46,
        81,
        94,
        -6.5,
        133.5,
        63,
        88
    ],
    "stats_score_o": [
        65,
        100,
        93,
        77,
        88,
        97,
        100,
        74.5,
        110.5,
        91,
        98
    ],
    "stats_score_s": [
        53,
        100,
        80,
        63,
        70,
        85,
        88,
        47.5,
        107.5,
        78,
        96
    ]
}