import { data, useLoaderData, useLocation } from "react-router"

import { getDynamoDB } from "~/common/utils/server/dynamodb.server"
import AuditReport from "~/site/ui/audit/report"
import { getStaticData } from "~/common/utils/server/get_static_data.server"
import { langByParam } from "~/common/shared/lang"
import type { Route } from "./+types/audits_ecos_v1_id"
import type { RouteHandle } from "types/site"
import NotFoundLang from "~/site/ui/core/other/notFoundLang"


export const handle: RouteHandle = {
    bc: true,
    page_key: "NS_ECOS_V1_ID"
};


export const loader = async ({ params }: Route.LoaderArgs) => {
    const { id, lang } = params
    const { lang_code } = langByParam(lang)

    const [audit_res, archive_res, stats_res, locTxt] = await Promise.all([
        getDynamoDB('page', id, "_table_audit_v1"),
        getDynamoDB("page-archive", id, "_table_audit_v1"),
        getDynamoDB('page-stats', 'main', '_table_audit_v1'),
        getStaticData(['loc_audits_v1_id'], lang_code)
    ])

    return data({
        audit: audit_res?.Item,
        archive: archive_res?.Item,
        stats: stats_res?.Item,
        locTxt: locTxt as Record<string, any>
    }, {
        status: audit_res?.Item ? 200 : 404,
    })
}


export default function Route() {
    const loaderData = useLoaderData()
    const { state } = useLocation()
    
    if (!loaderData?.audit && !state?.audit) return (
        <main className="main_container max-w-7xl m-auto relative pt-[44px]">
            <NotFoundLang />
        </main>
    )
    if (!loaderData?.stats || !loaderData?.archive) return (
        <main className="main_container max-w-7xl m-auto relative pt-[44px]">
            <h1>no stats or archive data</h1>
            <p>Are you running the App for the first time? The Page audit view requires stats on
                distribution and a urls history. Wait until they are generated by the CRON job or
                trigger this manually.</p>
        </main>
    )

    return (
        <>
            <AuditReport
                archive={loaderData.archive}
                auditResult={state?.audit ?? loaderData?.audit}
                pageStats={loaderData.stats}
            />
        </>

    )
}